name: cloudrun-deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true
    
    - name: Configure Docker
      run: |
        gcloud auth configure-docker
      
    - name: Build & Publish
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT }}
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }} --timeout=9000 --machine-type=n1-highcpu-32
      
    - name: Deploy
      run: |
        gcloud run deploy ${{ secrets.GCP_APPLICATION }} --image gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }} \
        --region=${{ secrets.REGION }} --platform managed --allow-unauthenticated
        gcloud run services update-traffic ${{ secrets.GCP_APPLICATION }} --region=${{ secrets.REGION }} --to-revisions LATEST=100